version: "3.5"
services:
  server:
    build:
      context: ./deploy
      dockerfile: Dockerfile
    working_dir: /server
    volumes:
      - .:/server
    ports:
      - "8080:8080"
    environment:
      - ENV=8080
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=user
      - DB_PASSWD=mysecretpassword
    depends_on:
      - db
    entrypoint: go run main.go
    restart: always
  db:
    image: postgres:12.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=mysecretpassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - bridger
networks:
  bridger:
    driver: bridge