// Code generated by go-swagger; DO NOT EDIT.

// Package restapi TimeSlot Manager
//
//  TimeSlot manager
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//    - application/timeslot.v1+json
//
//  Produces:
//    - application/json
//    - application/timeslot.v1+json
//
// swagger:meta
package restapi
