// Code generated by go-swagger; DO NOT EDIT.

package timeslot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// DestroyTimeslotURL generates an URL for the destroy timeslot operation
type DestroyTimeslotURL struct {
	TimeSlotID int64
	UserID     int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DestroyTimeslotURL) WithBasePath(bp string) *DestroyTimeslotURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *DestroyTimeslotURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *DestroyTimeslotURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/users/{user_id}/time-slots/{time_slot_id}"

	timeSlotID := swag.FormatInt64(o.TimeSlotID)
	if timeSlotID != "" {
		_path = strings.Replace(_path, "{time_slot_id}", timeSlotID, -1)
	} else {
		return nil, errors.New("timeSlotId is required on DestroyTimeslotURL")
	}

	userID := swag.FormatInt64(o.UserID)
	if userID != "" {
		_path = strings.Replace(_path, "{user_id}", userID, -1)
	} else {
		return nil, errors.New("userId is required on DestroyTimeslotURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *DestroyTimeslotURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *DestroyTimeslotURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *DestroyTimeslotURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on DestroyTimeslotURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on DestroyTimeslotURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *DestroyTimeslotURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
