// Code generated by go-swagger; DO NOT EDIT.

package timeslot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"codementordev/hello-johnhckuo/models"
)

// DestroyTimeslotNoContentCode is the HTTP code returned for type DestroyTimeslotNoContent
const DestroyTimeslotNoContentCode int = 204

/*DestroyTimeslotNoContent Deleted

swagger:response destroyTimeslotNoContent
*/
type DestroyTimeslotNoContent struct {
}

// NewDestroyTimeslotNoContent creates DestroyTimeslotNoContent with default headers values
func NewDestroyTimeslotNoContent() *DestroyTimeslotNoContent {

	return &DestroyTimeslotNoContent{}
}

// WriteResponse to the client
func (o *DestroyTimeslotNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*DestroyTimeslotDefault error

swagger:response destroyTimeslotDefault
*/
type DestroyTimeslotDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDestroyTimeslotDefault creates DestroyTimeslotDefault with default headers values
func NewDestroyTimeslotDefault(code int) *DestroyTimeslotDefault {
	if code <= 0 {
		code = 500
	}

	return &DestroyTimeslotDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the destroy timeslot default response
func (o *DestroyTimeslotDefault) WithStatusCode(code int) *DestroyTimeslotDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the destroy timeslot default response
func (o *DestroyTimeslotDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the destroy timeslot default response
func (o *DestroyTimeslotDefault) WithPayload(payload *models.Error) *DestroyTimeslotDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the destroy timeslot default response
func (o *DestroyTimeslotDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DestroyTimeslotDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
