// Code generated by go-swagger; DO NOT EDIT.

package timeslot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTimeslotHandlerFunc turns a function with the right signature into a get timeslot handler
type GetTimeslotHandlerFunc func(GetTimeslotParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTimeslotHandlerFunc) Handle(params GetTimeslotParams) middleware.Responder {
	return fn(params)
}

// GetTimeslotHandler interface for that can handle valid get timeslot params
type GetTimeslotHandler interface {
	Handle(GetTimeslotParams) middleware.Responder
}

// NewGetTimeslot creates a new http.Handler for the get timeslot operation
func NewGetTimeslot(ctx *middleware.Context, handler GetTimeslotHandler) *GetTimeslot {
	return &GetTimeslot{Context: ctx, Handler: handler}
}

/* GetTimeslot swagger:route GET /users/{user_id}/time-slots timeslot getTimeslot

Retrieve time slots based on userId & endAt filter

*/
type GetTimeslot struct {
	Context *middleware.Context
	Handler GetTimeslotHandler
}

func (o *GetTimeslot) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTimeslotParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
