// Code generated by go-swagger; DO NOT EDIT.

package timeslot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"codementordev/hello-johnhckuo/models"
)

// GetTimeslotOKCode is the HTTP code returned for type GetTimeslotOK
const GetTimeslotOKCode int = 200

/*GetTimeslotOK get available timeslots for the given user

swagger:response getTimeslotOK
*/
type GetTimeslotOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Timeslot `json:"body,omitempty"`
}

// NewGetTimeslotOK creates GetTimeslotOK with default headers values
func NewGetTimeslotOK() *GetTimeslotOK {

	return &GetTimeslotOK{}
}

// WithPayload adds the payload to the get timeslot o k response
func (o *GetTimeslotOK) WithPayload(payload []*models.Timeslot) *GetTimeslotOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get timeslot o k response
func (o *GetTimeslotOK) SetPayload(payload []*models.Timeslot) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTimeslotOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Timeslot, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*GetTimeslotDefault generic error response

swagger:response getTimeslotDefault
*/
type GetTimeslotDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTimeslotDefault creates GetTimeslotDefault with default headers values
func NewGetTimeslotDefault(code int) *GetTimeslotDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTimeslotDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get timeslot default response
func (o *GetTimeslotDefault) WithStatusCode(code int) *GetTimeslotDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get timeslot default response
func (o *GetTimeslotDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get timeslot default response
func (o *GetTimeslotDefault) WithPayload(payload *models.Error) *GetTimeslotDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get timeslot default response
func (o *GetTimeslotDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTimeslotDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
